-- initial_data.sql
-- MySQL statements to insert initial data into tables for a new installation.
-- statements MUST be separated by blank lines.
-- the token '[prefix]' will be replaced with the chosen table
-- prefix at installation time.

INSERT INTO `[prefix]lang` (`id`, `w`, `m`, `l`, `enc`) VALUES
(1, '$j phrases successfully added.', '$j phrases successfully added.', 'english', 'utf-8'),
(2, '$n items found', '$n items found', 'english', 'utf-8'),
(3, '$name has no known daughters.', '$name has no known daughters.', 'english', 'utf-8'),
(4, '$name has no known female offspring.', '$name has no known female offspring.', 'english', 'utf-8'),
(5, '$name has no known male offspring.', '$name has no known male offspring.', 'english', 'utf-8'),
(6, '$name has no known siblings.', '$name has no known siblings.', 'english', 'utf-8'),
(7, '$name has no known sons.', '$name has no known sons.', 'english', 'utf-8'),
(8, '$person1 and $person2 are brother and sister', '$person1 and $person2 are brother and sister', 'english', 'utf-8'),
(9, '$person1 is the $step brother of $person2', '$person1 is the $step brother of $person2', 'english', 'utf-8'),
(10, '$person1 is the $step sister of $person2', '$person1 is the $step sister of $person2', 'english', 'utf-8'),
(11, '$person1 is the spouse of $person2', '$person1 is the spouse of $person2', 'english', 'utf-8'),
(12, '''s', '''s', 'english', 'utf-8'),
(13, '''s record.', '''s record.', 'english', 'utf-8'),
(14, '(20 char. max)', '(20 char. max)', 'english', 'utf-8'),
(15, '(e.g BA History)', '(e.g BA History)', 'english', 'utf-8'),
(16, '(e.g. Catholic Church)', '(e.g. Catholic Church)', 'english', 'utf-8'),
(17, '(e.g. from Bogota, Colombia)', '(e.g. from Bogota, Colombia)', 'english', 'utf-8'),
(18, '(e.g. Hartford, CT)', '(e.g. Hartford, CT)', 'english', 'utf-8'),
(19, '(e.g. ill)', '(e.g. ill)', 'english', 'utf-8'),
(20, '(e.g. Love, Family Arragement)', '(e.g. Love, Family Arragement)', 'english', 'utf-8'),
(21, '(e.g. Normal, Ceasarian)', '(e.g. Normal, Ceasarian)', 'english', 'utf-8'),
(22, '(e.g. Presbyterian Church)', '(e.g. Presbyterian Church)', 'english', 'utf-8'),
(23, '(e.g. San Francisco, CA)', '(e.g. San Francisco, CA)', 'english', 'utf-8'),
(24, '(e.g. smith)', '(e.g. smith)', 'english', 'utf-8'),
(25, '(e.g. State College of New York)', '(e.g. State College of New York)', 'english', 'utf-8'),
(26, '(e.g. to Los Angeles, CA)', '(e.g. to Los Angeles, CA)', 'english', 'utf-8'),
(27, '(e.g. tumors in lungs and thyroid)', '(e.g. tumors in lungs and thyroid)', 'english', 'utf-8'),
(28, '(images exceeding dimensions of', '(images exceeding dimensions of', 'english', 'utf-8'),
(29, '(images exceeding dimensions of MAXPORTRAITWIDTH  x  MAXPORTRAITHEIGHT pixels will be resized)', '(images exceeding dimensions of MAXPORTRAITWIDTH  x  MAXPORTRAITHEIGHT pixels will be resized)', 'english', 'utf-8'),
(30, '(maximum size 1 MB, must be MS Word, PDF, or ASCII)', '(maximum size 1 MB, must be MS Word, PDF, or ASCII)', 'english', 'utf-8'),
(31, '(no breed specified)', '(no breed specified)', 'english', 'utf-8'),
(32, '(no name given)', '(no name given)', 'english', 'utf-8'),
(33, '(no owner specified)', '(no owner specified)', 'english', 'utf-8'),
(34, '(no surname given)', '(no surname given)', 'english', 'utf-8'),
(35, '(none)', '(none)', 'english', 'utf-8'),
(36, ', creator of TUFaT', ', creator of TUFaT', 'english', 'utf-8'),
(37, '...or...', '...or...', 'english', 'utf-8'),
(38, '10 Newest Individual Images', '10 Newest Individual Images', 'english', 'utf-8'),
(39, '10 Newest Individuals', '10 Newest Individuals', 'english', 'utf-8'),
(40, '10 Newest Tree Images', '10 Newest Tree Images', 'english', 'utf-8'),
(41, '10th', '10th', 'english', 'utf-8'),
(42, '1st', '1st', 'english', 'utf-8'),
(43, '1st Cousins:', '1st Cousins:', 'english', 'utf-8'),
(44, '2nd', '2nd', 'english', 'utf-8'),
(45, '3 = Highest Reliability', '3 = Highest Reliability', 'english', 'utf-8'),
(46, '3rd', '3rd', 'english', 'utf-8'),
(47, '4th', '4th', 'english', 'utf-8'),
(48, '5th', '5th', 'english', 'utf-8'),
(49, '6th', '6th', 'english', 'utf-8'),
(50, '7th', '7th', 'english', 'utf-8'),
(51, '8th', '8th', 'english', 'utf-8'),
(52, '9th', '9th', 'english', 'utf-8'),
(53, 'A relationship between $person1 and $person2 could not be found', 'A relationship between $person1 and $person2 could not be found', 'english', 'utf-8'),
(54, 'Add', 'Add', 'english', 'utf-8'),
(55, 'Add a Biography for', 'Add a Biography for', 'english', 'utf-8'),
(56, 'Add Citation', 'Add Citation', 'english', 'utf-8'),
(57, 'Add Dam Information', 'Add Dam Information', 'english', 'utf-8'),
(58, 'Add Father Information', 'Add Father Information', 'english', 'utf-8'),
(59, 'Add Item', 'Add Item', 'english', 'utf-8'),
(60, 'Add Links', 'Add Links', 'english', 'utf-8'),
(61, 'Add Mother Information', 'Add Mother Information', 'english', 'utf-8'),
(62, 'Add new  for', 'Add new  for', 'english', 'utf-8'),
(63, 'Add new Dam', 'Add new Dam', 'english', 'utf-8'),
(64, 'Add new Daughter', 'Add New Daughter', 'english', 'utf-8'),
(65, 'Add new Father', 'Add new Father', 'english', 'utf-8'),
(66, 'Add New Female Offspring', 'Add new Female offspring', 'english', 'utf-8'),
(67, 'Add New Image', 'Add New Image', 'english', 'utf-8'),
(68, 'Add new language record', 'Add new language record', 'english', 'utf-8'),
(69, 'Add new logins', 'Add new logins', 'english', 'utf-8'),
(70, 'Add New Male Offspring', 'Add new Male offspring', 'english', 'utf-8'),
(71, 'Add New Mate', 'Add new Mate', 'english', 'utf-8'),
(72, 'Add new Mother', 'Add new Mother', 'english', 'utf-8'),
(73, 'Add new Partner', 'Add new Partner', 'english', 'utf-8'),
(74, 'Add New Partner or Spouse', 'Add New Partner or Spouse', 'english', 'utf-8'),
(75, 'Add new Sibling', 'Add New Sibling', 'english', 'utf-8'),
(76, 'Add new Sire', 'Add new Sire', 'english', 'utf-8'),
(77, 'Add new Son', 'Add New Son', 'english', 'utf-8'),
(78, 'Add New Spouse or Life Partner', 'Add New Spouse or Life Partner', 'english', 'utf-8'),
(79, 'Add Notes', 'Add Notes', 'english', 'utf-8'),
(80, 'Add or Edit Gallery Images', 'Add or Edit Gallery Images', 'english', 'utf-8'),
(81, 'Add Sire Information', 'Add Sire Information', 'english', 'utf-8'),
(82, 'Add Sources', 'Add Sources', 'english', 'utf-8'),
(83, 'Add/Edit Events', 'Add/Edit Events', 'english', 'utf-8'),
(84, 'Additional Birth and Death Information', 'Additional Birth and Death Information', 'english', 'utf-8'),
(85, 'Address of Baptism', 'Address of Baptism', 'english', 'utf-8'),
(86, 'Address of Birth Site', 'Address of Birth Site', 'english', 'utf-8'),
(87, 'Address of Birthplace', 'Address of Birthplace', 'english', 'utf-8'),
(88, 'Address of Death Site', 'Address of Death Site', 'english', 'utf-8'),
(89, 'Address, line 1', 'Address, line 1', 'english', 'utf-8'),
(90, 'Address, line 2', 'Address, line 2', 'english', 'utf-8'),
(91, 'Address, line 3', 'Address, line 3', 'english', 'utf-8'),
(92, 'Admin E-mail Address:', 'Admin E-mail Address:', 'english', 'utf-8'),
(93, 'Administrative', 'Administrative', 'english', 'utf-8'),
(94, 'Administrative Password:', 'Administrative Password:', 'english', 'utf-8'),
(95, 'administrator', 'administrator', 'english', 'utf-8'),
(96, 'Administrator Fields', 'Administrator Fields', 'english', 'utf-8'),
(97, 'Administrator''s Name:', 'Administrator''s Name:', 'english', 'utf-8'),
(98, 'adminname', 'Administrator', 'english', 'utf-8'),
(99, 'Adoption Citations', 'Adoption Citations', 'english', 'utf-8'),
(100, 'Adoption Notes', 'Adoption Notes', 'english', 'utf-8'),
(101, 'Adoption Notes and Citations', 'Adoption Notes and Citations', 'english', 'utf-8'),
(102, 'Adoption Notes and Sources', 'Adoption Notes and Sources', 'english', 'utf-8'),
(103, 'Adoption Sources', 'Adoption Sources', 'english', 'utf-8'),
(104, 'Adult Christening', 'Adult Christening', 'english', 'utf-8'),
(105, 'Age at Baptism', 'Age at Baptism', 'english', 'utf-8'),
(106, 'Agency of Baptism', 'Agency of Baptism', 'english', 'utf-8'),
(107, 'Alive', 'Alive', 'english', 'utf-8'),
(108, 'All done', 'All done', 'english', 'utf-8'),
(109, 'All other trees in the database will be left intact.', 'All other trees in the database will be left intact.', 'english', 'utf-8'),
(110, 'Allow Cross-tree Searches?', 'Allow Cross-tree Searches?', 'english', 'utf-8'),
(111, 'An Error Has Occurred', 'An Error Has Occurred', 'english', 'utf-8'),
(112, 'An update has been made to your record in the family tree!', 'An update has been made to your record in the family tree!', 'english', 'utf-8'),
(113, 'and', 'and', 'english', 'utf-8'),
(114, 'animal', 'animal', 'english', 'utf-8'),
(115, 'Animal Name', 'Animal Name', 'english', 'utf-8'),
(116, 'Annulment', 'Annulment', 'english', 'utf-8'),
(117, 'any existing portrait or biography for this individual.', 'any existing portrait or biography for this individual.', 'english', 'utf-8'),
(118, 'Are you sure you would like to remove this item ?', 'Are you sure you would like to remove this item ?', 'english', 'utf-8'),
(119, 'Are you sure? Citations based on this source will also be removed.', 'Are you sure? Citations based on this source will also be removed.', 'english', 'utf-8'),
(120, 'as the recipient address.', 'as the recipient address.', 'english', 'utf-8'),
(121, 'aunt', 'aunt', 'english', 'utf-8'),
(122, 'aunts', 'aunts', 'english', 'utf-8'),
(123, 'Aunts &amp; Uncles:', 'Aunts &amp; Uncles:', 'english', 'utf-8'),
(124, 'aunts and uncles', 'aunts and uncles', 'english', 'utf-8'),
(125, 'Author', 'Author', 'english', 'utf-8'),
(126, 'b. Date: $birt_date', 'b. Date: $birt_date', 'english', 'utf-8'),
(127, 'b. Place: $birt_plac', 'b. Place: $birt_plac', 'english', 'utf-8'),
(128, 'Back', 'Back', 'english', 'utf-8'),
(129, 'Backup All Trees', 'Backup All Trees', 'english', 'utf-8'),
(130, 'Baptised?', 'Baptised?', 'english', 'utf-8'),
(131, 'Baptism Citations', 'Baptism Citations', 'english', 'utf-8'),
(132, 'Baptism Notes', 'Baptism Notes', 'english', 'utf-8'),
(133, 'Baptism Notes and Citations', 'Baptism Notes and Citations', 'english', 'utf-8'),
(134, 'Baptism Notes and Sources', 'Baptism Notes and Sources', 'english', 'utf-8'),
(135, 'Baptism Sources', 'Baptism Sources', 'english', 'utf-8'),
(136, 'Baptism, Christening, and Bar/Bat Mitzvah Information', 'Baptism, Christening, and Bar/Bat Mitzvah Information', 'english', 'utf-8'),
(137, 'Baptismal Date', 'Baptismal Date', 'english', 'utf-8'),
(138, 'Baptismal Place', 'Baptismal Place', 'english', 'utf-8'),
(139, 'Bar/Bat Mitzvah Citations', 'Bar/Bat Mitzvah Citations', 'english', 'utf-8'),
(140, 'Bar/Bat Mitzvah Date', 'Bar/Bat Mitzvah Date', 'english', 'utf-8'),
(141, 'Bar/Bat Mitzvah Note', 'Bar/Bat Mitzvah Note', 'english', 'utf-8'),
(142, 'Bar/Bat Mitzvah Notes', 'Bar/Bat Mitzvah Notes', 'english', 'utf-8'),
(143, 'Bar/Bat Mitzvah Notes and Citations', 'Bar/Bat Mitzvah Notes and Citations', 'english', 'utf-8'),
(144, 'Bar/Bat Mitzvah Notes and Sources', 'Bar/Bat Mitzvah Notes and Sources', 'english', 'utf-8'),
(145, 'Bar/Bat Mitzvah Place', 'Bar/Bat Mitzvah Place', 'english', 'utf-8'),
(146, 'Bar/Bat Mitzvah Sources', 'Bar/Bat Mitzvah Sources', 'english', 'utf-8'),
(147, 'big_upload_info1', 'If your GEDCOM file is very large (>500KB), then you may upload the file in multiple parts. Each part should be less than 500KB, and you should divide the files so that individual GEDCOM records are not divided into separate files. GEDCOM records typically start with "0", for example:', 'english', 'utf-8'),
(148, 'big_upload_info2', 'When all files have been separately uploaded, click "All Done". This will', 'english', 'utf-8'),
(149, 'big_upload_info3', 'erase all data that is currently present, replacing it with imported data.', 'english', 'utf-8'),
(150, 'Birth Citations', 'Birth Citations', 'english', 'utf-8'),
(151, 'Birth Date', 'Birth Date', 'english', 'utf-8'),
(152, 'Birth Date can''t be later than today', 'Birth Date can''t be later than today', 'english', 'utf-8'),
(153, 'Birth Note', 'Birth Note', 'english', 'utf-8'),
(154, 'Birth Notes', 'Birth Notes', 'english', 'utf-8'),
(155, 'Birth Notes and Citations', 'Birth Notes and Citations', 'english', 'utf-8'),
(156, 'Birth Notes and Sources', 'Birth Notes and Sources', 'english', 'utf-8'),
(157, 'Birth Place', 'Birth Place', 'english', 'utf-8'),
(158, 'Birth Sources', 'Birth Sources', 'english', 'utf-8'),
(159, 'Blessing', 'Blessing', 'english', 'utf-8'),
(160, 'born between', 'born between', 'english', 'utf-8'),
(161, 'born during this month', 'born during this month', 'english', 'utf-8'),
(162, 'born on this day', 'born on this day', 'english', 'utf-8'),
(163, 'Breed', 'Breed', 'english', 'utf-8'),
(164, 'breed fragment', 'breed fragment', 'english', 'utf-8'),
(165, 'Breeder', 'Breeder', 'english', 'utf-8'),
(166, 'Bump Up', 'Bump Up', 'english', 'utf-8'),
(167, 'burial place fragment', 'burial place fragment', 'english', 'utf-8'),
(168, 'Burial Site', 'Burial Site', 'english', 'utf-8'),
(169, 'Call Name', 'Call Name', 'english', 'utf-8'),
(170, 'Call number', 'Call number', 'english', 'utf-8'),
(171, 'Callname', 'Call Name', 'english', 'utf-8'),
(172, 'callname fragment', 'call name fragment', 'english', 'utf-8'),
(173, 'Cancel', 'Cancel', 'english', 'utf-8'),
(174, 'Cannot establish connection to the database (invalid username, password, or hostname)', 'Cannot establish connection to the database (invalid username, password, or hostname)', 'english', 'utf-8'),
(175, 'Cannot find database $dbName (invalid database name)', 'Cannot find database $dbName (invalid database name)', 'english', 'utf-8'),
(176, 'Caption:', 'Caption:', 'english', 'utf-8'),
(177, 'cap_Gender', 'Gender', 'english', 'utf-8'),
(178, 'cause of death', 'Cause of Death', 'english', 'utf-8'),
(179, 'Cause of Marriage', 'Cause of Marriage', 'english', 'utf-8'),
(180, 'Census', 'Census', 'english', 'utf-8'),
(181, 'Championship Titles', 'Championship Titles', 'english', 'utf-8'),
(182, 'Change', 'Change', 'english', 'utf-8'),
(183, 'Change Father', 'Change Father', 'english', 'utf-8'),
(184, 'Change Mother', 'Change Mother', 'english', 'utf-8'),
(185, 'Change Template', 'Change Template', 'english', 'utf-8'),
(186, 'Change type', 'Change type', 'english', 'utf-8'),
(187, 'checked', 'checked', 'english', 'utf-8'),
(188, 'checking_this_box', 'Checking this box will give the general public a very limited, read-only view of your tree when performing searches. They will still need to contact you, the tree administrator, to gain access to the tree.', 'english', 'utf-8'),
(189, 'Children:', 'Children:', 'english', 'utf-8'),
(190, 'chliv_txt_1', 'This setting affects only those individuals in your family tree for which the "Hide Individual" checkbox has been selected.', 'english', 'utf-8'),
(191, 'Choose a User ID:', 'Choose a User ID:', 'english', 'utf-8'),
(192, 'Choose Template', 'Choose Template', 'english', 'utf-8'),
(193, 'Citation # $mid has been deleted successfully.', 'Citation # $mid has been deleted successfully.', 'english', 'utf-8'),
(194, 'Citation delete problem.', 'Citation delete problem.', 'english', 'utf-8'),
(195, 'Citations', 'Citations', 'english', 'utf-8'),
(196, 'City', 'City', 'english', 'utf-8'),
(197, 'Click a name to load the person''s record, or click on a column header to re-sort the search results.', 'Click a name to load the person''s record, or click on a column to re-sort the search results.', 'english', 'utf-8'),
(198, 'Click here to add one.', 'Click here to add one.', 'english', 'utf-8'),
(199, 'click here to create one', 'click here to create one', 'english', 'utf-8'),
(200, 'Click here to log back in', 'Click here to log back in', 'english', 'utf-8'),
(201, 'Click here to view your entire tree', 'Click here to view your entire tree', 'english', 'utf-8'),
(202, 'Click on an individual''s name to load the record. You may return to this page at any time by clicking the ''Entire Tree'' link at the left. Records are sorted here by family name, although different families who share a family name are placed together.', 'Click on an individual''s name to load the record. You may return to this page at any time by clicking the ''Entire Tree'' link at the left. Records are sorted here by family name, although different families who share a family name are placed together.', 'english', 'utf-8'),
(203, 'Clicking on the name of an individual will give you a form by which you can request access to the tree by the tree administrator. For security reasons, you may not access trees outside your own family without permission of the tree owner, and only initials and years are provided in lieu of full names and dates. Highlighted rows indicate a likely match to the currently loaded tree.', 'Clicking on the name of an individual will give you a form by which you can request access to the tree by the tree administrator. For security reasons, you may not access trees outside your own family without permission of the tree owner, and only initials and years are provided in lieu of full names and dates. Highlighted rows indicate a likely match to the currently loaded tree.', 'english', 'utf-8'),
(204, 'click_on_a_name', 'Clicking on a name in the extended tree will re-center the tree\r\n            around that individual. To view a record, click on the person''s name\r\n            once to re-enter the extended tree, then click on the name at the\r\n            base of the tree (the large link) to load the record.', 'english', 'utf-8'),
(205, 'Close this Window', 'Close this Window', 'english', 'utf-8'),
(206, 'Close Windows', 'Close Windows', 'english', 'utf-8'),
(207, 'cmp_upload_info1', 'If your GEDCOM file is very large, you may compress it first as a tar.gz file, and then upload the compressed file. Select "Append to existing tree" to append the data to the currently loaded family tree.', 'english', 'utf-8'),
(208, 'cmp_upload_info2', 'Other wise, the imported GEDCOM information will', 'english', 'utf-8'),
(209, 'cmp_upload_info3', 'erase all data that is currently present, replacing it with imported data.', 'english', 'utf-8'),
(210, 'Comapct', 'Compact', 'english', 'utf-8'),
(211, 'Comments', 'Comments', 'english', 'utf-8'),
(212, 'Complete This Information to Create a New Tree', 'Complete This Information to Create a New Tree', 'english', 'utf-8'),
(213, 'COMPLETELY', 'COMPLETELY', 'english', 'utf-8'),
(214, 'Confirmation Citations', 'Confirmation Citations', 'english', 'utf-8'),
(215, 'Confirmation Date', 'Confirmation Date', 'english', 'utf-8'),
(216, 'Confirmation Notes', 'Confirmation Notes', 'english', 'utf-8'),
(217, 'Confirmation Notes and Citations', 'Confirmation Notes and Citations', 'english', 'utf-8'),
(218, 'Confirmation Notes and Sources', 'Confirmation Notes and Sources', 'english', 'utf-8'),
(219, 'Confirmation Place', 'Confirmation Place', 'english', 'utf-8'),
(220, 'Confirmation Sources', 'Confirmation Sources', 'english', 'utf-8'),
(221, 'Congratulations! The e-mail to $semail was sent successfully', 'Congratulations! The e-mail to $semail was sent successfully', 'english', 'utf-8'),
(222, 'Contact Information (last known)', 'Contact Information (last known)', 'english', 'utf-8'),
(223, 'Contact Information:', 'Contact Information:', 'english', 'utf-8'),
(224, 'Country', 'Country', 'english', 'utf-8'),
(225, 'cousin', 'cousin', 'english', 'utf-8'),
(226, 'cousins', 'cousins', 'english', 'utf-8'),
(227, 'Create a new member in the tree', 'Create a new member in the tree', 'english', 'utf-8'),
(228, 'Create a new person in your tree', 'Create a new person in your tree', 'english', 'utf-8'),
(229, 'Create a new record in this family tree', 'Create a new record in this family tree', 'english', 'utf-8'),
(230, 'Create new login', 'Create new login', 'english', 'utf-8'),
(231, 'Create the first person in your tree', 'Create the first person in your tree', 'english', 'utf-8'),
(232, 'Create the first record in this family tree', 'Create the first record in this family tree', 'english', 'utf-8'),
(233, 'Cremation', 'Cremation', 'english', 'utf-8'),
(234, 'cshow_h', 'The purpose of this view is to enable quick identification of your family''s cousins from different generations, and across multiple degrees of removal. To save space, cousins are not distinguished by family; instead, all cousins of a particular type are grouped into the same block. You must have at least Internet Explorer 5+ or Netscape 7+ to correctly use this tree view. Position the mouse over a rectangle to see the individuals with that designation, and click on an individual''s name to re-center the tree around that individual.', 'english', 'utf-8'),
(235, 'Dam', 'Dam', 'english', 'utf-8'),
(236, 'Dam:', 'Dam:', 'english', 'utf-8'),
(237, 'Date', 'Date', 'english', 'utf-8'),
(238, 'Date can''t be later than today', 'Date can''t be later than today', 'english', 'utf-8'),
(239, 'Date of Adoption', 'Date of Adoption', 'english', 'utf-8'),
(240, 'Date of Baptism', 'Date of Baptism', 'english', 'utf-8'),
(241, 'Date of Bar/Bat Mitzvah', 'Date of Bar/Bat Mitzvah', 'english', 'utf-8'),
(242, 'Date of Birth', 'Date of Birth', 'english', 'utf-8'),
(243, 'Date of Death', 'Date of Death', 'english', 'utf-8'),
(244, 'Date of Graduation', 'Date of Graduation', 'english', 'utf-8'),
(245, 'Date of Immigration', 'Date of Immigration', 'english', 'utf-8'),
(246, 'Date of Last Change', 'Date of Last Change', 'english', 'utf-8'),
(247, 'Daughters', 'Daughters', 'english', 'utf-8'),
(248, 'Dead', 'Dead', 'english', 'utf-8'),
(249, 'Dear $matchTree tree administrator, A search of the family tree database on $sname suggests that we have a common link in our family trees. The record in your tree with ID# $ID may match a record in the $user tree may match a record in the family tree. I am interested in pursuing this possibility to find common ancestors and relations between our families. Thanks!', 'Dear $matchTree tree administrator,\r\n A search of the family tree database on $sname suggests that we have a common link in our family trees. The record in your tree with ID# $ID may match a record in the $user tree may match a record in the family tree. I am interested in pursuing this possibility to find common ancestors and relations between our families. Thanks!', 'english', 'utf-8'),
(250, 'Death Citations', 'Death Citations', 'english', 'utf-8'),
(251, 'Death Date', 'Death Date', 'english', 'utf-8'),
(252, 'Death Date can''t be before Birth Date', 'Death Date can''t be before Birth Date', 'english', 'utf-8'),
(253, 'Death Date can''t be entered for an alive person', 'Death Date can''t be entered for an alive person', 'english', 'utf-8'),
(254, 'Death Date can''t be later than today', 'Death Date can''t be later than today', 'english', 'utf-8'),
(255, 'Death Note', 'Death Note', 'english', 'utf-8'),
(256, 'Death Notes', 'Death Notes', 'english', 'utf-8'),
(257, 'Death Notes and Citations', 'Death Notes and Citations', 'english', 'utf-8'),
(258, 'Death Notes and Sources', 'Death Notes and Sources', 'english', 'utf-8'),
(259, 'Death Sources', 'Death Sources', 'english', 'utf-8'),
(260, 'Death Status  (if unknown)', 'Death Status  (if unknown)', 'english', 'utf-8'),
(261, 'Degree', 'Degree', 'english', 'utf-8'),
(262, 'Delete', 'Delete', 'english', 'utf-8'),
(263, 'Delete This Tree', 'Delete This Tree', 'english', 'utf-8'),
(264, 'Deletion problem', 'Deletion problem', 'english', 'utf-8'),
(265, 'demo', 'demo', 'english', 'utf-8'),
(266, 'Description:', 'Description:', 'english', 'utf-8'),
(267, 'Descriptive Tree Name:', 'Descriptive Tree Name:', 'english', 'utf-8'),
(268, 'died between', 'died between', 'english', 'utf-8'),
(269, 'disabled', 'disabled', 'english', 'utf-8'),
(270, 'Dissolve Marriage', 'Dissolve Marriage', 'english', 'utf-8'),
(271, 'Divorce', 'Divorce', 'english', 'utf-8'),
(272, 'Divorce Citations', 'Divorce Citations', 'english', 'utf-8'),
(273, 'Divorce Date', 'Divorce Date', 'english', 'utf-8'),
(274, 'Divorce Filing', 'Divorce Filing', 'english', 'utf-8'),
(275, 'Divorce Information', 'Divorce Information', 'english', 'utf-8'),
(276, 'Divorce Notes', 'Divorce Notes', 'english', 'utf-8'),
(277, 'Divorce Notes and Citations', 'Divorce Notes and Citations', 'english', 'utf-8'),
(278, 'Divorce Notes and Sources', 'Divorce Notes and Sources', 'english', 'utf-8'),
(279, 'Divorce Sources', 'Divorce Sources', 'english', 'utf-8'),
(280, 'Divorce, Engagement, and additional Marriage Information', 'Divorce, Engagement, and additional Marriage Information', 'english', 'utf-8'),
(281, 'Divorced', 'Divorced', 'english', 'utf-8'),
(282, 'Divorced?', 'Divorced?', 'english', 'utf-8'),
(283, 'Do NOT delete this tree!', 'Do NOT delete this tree!', 'english', 'utf-8'),
(284, 'Do not spam or flame the tree administrator.', 'Do not spam or flame the tree administrator.', 'english', 'utf-8'),
(285, 'Download Biography', 'Download Biography', 'english', 'utf-8'),
(286, 'do_not_attempt', 'Do not attempt to gain access to family trees\r\n    for which you do not have access.', 'english', 'utf-8'),
(287, 'do_not_post', 'Do not post inappropriate material on a tree, as minors may\r\n    be viewing them.', 'english', 'utf-8'),
(288, 'E-Mail', 'E-Mail', 'english', 'utf-8'),
(289, 'E-Mail address', 'E-Mail Address', 'english', 'utf-8'),
(290, 'E-Mail From', 'E-Mail From', 'english', 'utf-8'),
(291, 'E-Mail not valid', 'E-Mail not valid', 'english', 'utf-8'),
(292, 'E-Mail sending problem', 'E-Mail sending problem', 'english', 'utf-8'),
(293, 'E-Mail Subject', 'E-Mail Subject', 'english', 'utf-8'),
(294, 'E-mail this person any time this record is updated.', 'E-mail this person any time this record is updated.', 'english', 'utf-8'),
(295, 'E-Mail To', 'E-Mail To', 'english', 'utf-8'),
(296, 'E-Mail To address invalid', 'E-Mail To address invalid', 'english', 'utf-8'),
(297, 'EAEAD2', 'EAEAD2', 'english', 'utf-8'),
(298, 'Edit Data for', 'Edit Data for', 'english', 'utf-8'),
(299, 'Edit Data for $name', 'Edit Data for $name', 'english', 'utf-8'),
(300, 'Edit Events', 'Edit Events', 'english', 'utf-8'),
(301, 'Edit Existing Image(s)', 'Edit Existing Image(s)', 'english', 'utf-8'),
(302, 'Edit individual ID', 'Edit individual ID', 'english', 'utf-8'),
(303, 'Edit life events', 'Edit life events', 'english', 'utf-8'),
(304, 'Edit Marriage or Partnership Data', 'Edit Marriage or Partnership Data', 'english', 'utf-8'),
(305, 'Edit Marriage or Partnership Information', 'Edit Marriage or Partnership Information', 'english', 'utf-8'),
(306, 'Edit Note # $sid', 'Edit Note # $sid', 'english', 'utf-8'),
(307, 'Edit Only', 'Edit Only', 'english', 'utf-8'),
(308, 'Edit Partnership Data', 'Edit Partnership Data', 'english', 'utf-8'),
(309, 'Edit Partnership Information', 'Edit Partnership Information', 'english', 'utf-8'),
(310, 'Edit Passwords', 'Edit Passwords', 'english', 'utf-8'),
(311, 'Edit Personal Data for', 'Edit Personal Data for', 'english', 'utf-8'),
(312, 'Edit Personal Data for $name', 'Edit Personal Data for $name', 'english', 'utf-8'),
(313, 'Edit Source', 'Edit Source', 'english', 'utf-8'),
(314, 'Edit This Record', 'Edit This Record', 'english', 'utf-8'),
(315, 'Edit User Information', 'Edit User Information', 'english', 'utf-8'),
(316, 'edit_ilog_id', 'If "Edit Individual Record ID" is chosen from the drop-down list, then you MUST enter a valid record ID. The user will only be able to edit the record with the provided record ID.', 'english', 'utf-8'),
(317, 'eighth', 'eighth', 'english', 'utf-8'),
(318, 'Emigration', 'Emigration', 'english', 'utf-8'),
(319, 'enabled', 'enabled', 'english', 'utf-8'),
(320, 'Engagement', 'Engagement', 'english', 'utf-8'),
(321, 'Enjoy!', 'Enjoy!', 'english', 'utf-8'),
(322, 'Enjoy, and thanks for using the system!', 'Enjoy, and thanks for using the system!', 'english', 'utf-8'),
(323, 'Entire Tree / Index', 'Entire Tree / Index', 'english', 'utf-8'),
(324, 'erase_all_data', 'erase all data that is currently in the tree. If you want to save\r\n the current data, then you should create a new tree or backup the\r\n existing tree.', 'english', 'utf-8'),
(325, 'err1_impp', 'The system was unable to upload your file. This may be due to a corrupted\r\n\r\narchive or invalid archive format, or a file size that exceeds the maximum\r\n\r\nallowed file upload size, as determined by your server. Please check to\r\n\r\nensure that the archive is an intact tar.gz archive, and also that the\r\n\r\nPHP_INI_SYSTEM server variable is sufficiently large for this file upload.\r\n\r\nIt may also be necessary to check your web server configuration, for example\r\n\r\nthe http.conf file in Apache.', 'english', 'utf-8'),
(326, 'ERROR IN:', 'ERROR IN:', 'english', 'utf-8'),
(327, 'err_extr_gzip', 'There has been an error in decompressing the file. It''s possible that your web server cannot decompress the tar.gz format, or that the files were not compressed using the tar.gz format', 'english', 'utf-8'),
(328, 'Essential Information', 'Essential Information', 'english', 'utf-8'),
(329, 'Event', 'Event', 'english', 'utf-8'),
(330, 'Events', 'Events', 'english', 'utf-8'),
(331, 'Existing', 'Existing', 'english', 'utf-8'),
(332, 'Export a Language File', 'Export a Language File', 'english', 'utf-8'),
(333, 'Export as ZIP', 'Export as ZIP', 'english', 'utf-8'),
(334, 'Export compressed', 'Export compressed', 'english', 'utf-8'),
(335, 'Export individual portraits to a tar.gz or .zip file', 'Export individual portraits to a tar.gz or .zip file', 'english', 'utf-8'),
(336, 'Export Language', 'Export Language', 'english', 'utf-8'),
(337, 'Export to GEDCOM', 'Export to GEDCOM', 'english', 'utf-8'),
(338, 'Export your tree to the GEDCOM format', 'Export your tree to the GEDCOM format', 'english', 'utf-8'),
(339, 'expp_txt_1', 'This tool allows a mass-export of your family tree portraits to a file for easy backup and sharing. It is recommended that you do this when a GEDCOM export is performed, so that you can easily restore all of your family''s portraits.', 'english', 'utf-8'),
(340, 'Extended Family', 'Extended Family', 'english', 'utf-8'),
(341, 'Family Chart', 'Family Chart', 'english', 'utf-8'),
(342, 'Family Gallery', 'Family Gallery', 'english', 'utf-8'),
(343, 'Family members', 'Family members', 'english', 'utf-8'),
(344, 'Family Tree', 'Family Tree', 'english', 'utf-8'),
(345, 'Family Tree Administrator', 'Family Tree Administrator', 'english', 'utf-8'),
(346, 'father', 'father', 'english', 'utf-8'),
(347, 'Father', 'Father', 'english', 'utf-8'),
(348, 'Father:', 'Father:', 'english', 'utf-8'),
(349, 'Female', 'Female', 'english', 'utf-8'),
(350, 'Female offspring', 'Female offspring', 'english', 'utf-8'),
(351, 'fifth', 'fifth', 'english', 'utf-8'),
(352, 'File', 'File', 'english', 'utf-8'),
(353, 'File Name', 'File Name', 'english', 'utf-8'),
(354, 'File Name:', 'File Name:', 'english', 'utf-8'),
(355, 'File:', 'File:', 'english', 'utf-8'),
(356, 'Find another relation in your family tree', 'Find another relation in your family tree', 'english', 'utf-8'),
(357, 'Find Relation', 'Find Relation', 'english', 'utf-8'),
(358, 'Find relation between', 'Find relation between', 'english', 'utf-8'),
(359, 'first', 'first', 'english', 'utf-8'),
(360, 'for_10000', 'For about\r\n        10,000 man-hours of programming time, that''s a pretty good deal! If you\r\n        would like me to help you install it on your web server, it''s an additional\r\n        $49 for installation on either a UNIX or Windows server. All payments\r\n        can be made through Paypal, using', 'english', 'utf-8'),
(361, 'for_the_best', 'A ''fragment'' is a single word,\r\n            or even just a part of a word, that identifies the item. For example,\r\n            if searching for all people named William, you might chose simple\r\n            &quot;ill&quot; as the name fragment, since this would match &quot;Bill&quot;\r\n            as well as &quot;William&quot; and &quot;Billy&quot;. To view all\r\n            records, leave all fields blank.', 'english', 'utf-8'),
(362, 'fourth', 'fourth', 'english', 'utf-8'),
(363, 'ftp_upload_info', 'Specify full HTTP, FTP or server path address for the GEDCOM file. For example: <br />FTP Path: ftp://user:password@ftp.myftp.com/mytree.ged<br />HTTP Path: http://myserver/mytree.ged<br />Server Path: /home/myaccount/public_html/mytree.ged', 'english', 'utf-8'),
(364, 'Full Name:', 'Full Name:', 'english', 'utf-8'),
(365, 'GEDCOM ID', 'GEDCOM ID', 'english', 'utf-8'),
(366, 'Gender', 'Gender', 'english', 'utf-8'),
(367, 'gender', 'gender', 'english', 'utf-8'),
(368, 'General Edit', 'General Edit', 'english', 'utf-8'),
(369, 'General Use Password:', 'General Use Password:', 'english', 'utf-8'),
(370, 'Generate this tree from an imported GEDCOM file', 'Generate this tree from an imported GEDCOM file', 'english', 'utf-8'),
(371, 'Generations', 'Generations', 'english', 'utf-8'),
(372, 'Given Name', 'Given Name', 'english', 'utf-8'),
(373, 'Given names (first &amp; middle)', 'Given names (first &amp; middle)', 'english', 'utf-8'),
(374, 'Graduation', 'Graduation', 'english', 'utf-8'),
(375, 'Graduation Citations', 'Graduation Citations', 'english', 'utf-8'),
(376, 'Graduation Date', 'Graduation Date', 'english', 'utf-8'),
(377, 'Graduation Description', 'Graduation Description', 'english', 'utf-8'),
(378, 'Graduation Notes', 'Graduation Notes', 'english', 'utf-8'),
(379, 'Graduation Notes and Citations', 'Graduation Notes and Citations', 'english', 'utf-8'),
(380, 'Graduation Notes and Sources', 'Graduation Notes and Sources', 'english', 'utf-8'),
(381, 'Graduation Sources', 'Graduation Sources', 'english', 'utf-8'),
(382, 'Graduation, baptism, military service, retirement, and other life events.', 'Graduation, baptism, military service, retirement, and other life events.', 'english', 'utf-8'),
(383, 'grand', 'grand', 'english', 'utf-8'),
(384, 'Grandchildren:', 'Grandchildren:', 'english', 'utf-8'),
(385, 'great', 'great', 'english', 'utf-8'),
(386, 'Great, great grandparents:', 'Great, great grandparents:', 'english', 'utf-8'),
(387, 'Guidelines', 'Guidelines', 'english', 'utf-8'),
(388, 'has no known daughters.', 'has no known daughters.', 'english', 'utf-8'),
(389, 'has no known female offspring.', 'has no known female offspring.', 'english', 'utf-8'),
(390, 'has no known male offspring.', 'has no known male offspring.', 'english', 'utf-8'),
(391, 'has no known siblings.', 'has no known siblings.', 'english', 'utf-8'),
(392, 'has no known sons.', 'has no known sons.', 'english', 'utf-8'),
(393, 'Health Information', 'Health Information', 'english', 'utf-8'),
(394, 'Help', 'Help', 'english', 'utf-8'),
(395, 'here', 'here', 'english', 'utf-8'),
(396, 'Help Me!', 'Help Me!', 'english', 'utf-8'),
(397, 'Hide', 'Hide', 'english', 'utf-8'),
(398, 'Hide Individual', 'Hide Individual', 'english', 'utf-8'),
(399, 'Hide Living', 'Hide Living', 'english', 'utf-8'),
(400, 'Hide Living Status', 'Hide Living Status', 'english', 'utf-8'),
(401, 'Hide Type', 'Hide Type', 'english', 'utf-8'),
(402, 'hid_indi', 'Information for the individual is hidden', 'english', 'utf-8'),
(403, 'hop1', 'Hide everything except first letters', 'english', 'utf-8'),
(404, 'hop2', 'Hide everything', 'english', 'utf-8'),
(405, 'hop3', 'Hide middle and last name', 'english', 'utf-8'),
(406, 'hop4', 'Hide everything except name', 'english', 'utf-8'),
(407, 'hop5', 'Hide photo only', 'english', 'utf-8'),
(408, 'How can I enter adopted\r\n        births or domestic partners?', 'How can I enter adopted\r\n        births or domestic partners?', 'english', 'utf-8'),
(409, 'How can I enter adopted births or domestic partners?', 'How can I enter adopted births or domestic partners?', 'english', 'utf-8'),
(410, 'How can I print my family\r\ntree?', 'How can I print my family\r\ntree?', 'english', 'utf-8'),
(411, 'How can I print my family tree?', 'How can I print my family tree?', 'english', 'utf-8'),
(412, 'How do I get a copy of this software for my own website?', 'How do I get a copy of this software for my own website?', 'english', 'utf-8'),
(413, 'How do I log out of the system?', 'How do I log out of the system?', 'english', 'utf-8'),
(414, 'How do I log out of TUFaT', 'How do I log out of TUFaT', 'english', 'utf-8'),
(415, 'How do I upload a photo\r\nto the tree?', 'How do I upload a photo\r\nto the tree?', 'english', 'utf-8'),
(416, 'How do I upload a photo to the tree?', 'How do I upload a photo to the tree?', 'english', 'utf-8'),
(417, 'How often is my family tree backed up?', 'How often is my family tree backed up?', 'english', 'utf-8'),
(418, 'HTML tags are not allowed', 'HTML tags are not allowed', 'english', 'utf-8'),
(419, 'Husband or Male Partner', 'Husband or Male Partner', 'english', 'utf-8'),
(420, 'I have a very large tree and want to jump to a specific person.', 'I have a very large tree and want to jump to a specific person.', 'english', 'utf-8'),
(421, 'I have read and agree with the guidelines:', 'I have read and agree with the guidelines:', 'english', 'utf-8'),
(422, 'I uploaded a biography but it comes out as garbage.', 'I uploaded a biography but it comes out as garbage.', 'english', 'utf-8'),
(423, 'If this daughter is already present in the family database, then please select the person from this list:', 'If this daughter is already present in the family database, then please select the person from this list:', 'english', 'utf-8'),
(424, 'If this father is already present in the family database, then please select the person from this list:', 'If this father is already present in the family database, then please select the person from this list:', 'english', 'utf-8'),
(425, 'If this is a recurring error, please', 'If this is a recurring error, please', 'english', 'utf-8'),
(426, 'If this mother is already present in the family database, then please select the person from this list:', 'If this mother is already present in the family database, then please select the person from this list:', 'english', 'utf-8'),
(427, 'If this sibling is already present in the family database, then please select the person from this list:', 'If this sibling is already present in the family database, then please select the person from this list:', 'english', 'utf-8'),
(428, 'If this son is already present in the family database, then please select the person from this list:', 'If this son is already present in the family database, then please select the person from this list:', 'english', 'utf-8'),
(429, 'If this spouse is already present in the family database, then please select the person from this list:', 'If this spouse is already present in the family database, then please select the person from this list:', 'english', 'utf-8'),
(430, 'if_you_like_to', 'If you would like to license this software for your\r\n        own website, you can get a copy with 100% of the source code for only\r\n        $5 at', 'english', 'utf-8'),
(431, 'Image Gallery', 'Image Gallery', 'english', 'utf-8'),
(432, 'Immigration', 'Immigration', 'english', 'utf-8'),
(433, 'Immigration Citations', 'Immigration Citations', 'english', 'utf-8'),
(434, 'Immigration Date', 'Immigration Date', 'english', 'utf-8'),
(435, 'Immigration Description', 'Immigration Description', 'english', 'utf-8'),
(436, 'Immigration Destination', 'Immigration Destination', 'english', 'utf-8'),
(437, 'Immigration Notes', 'Immigration Notes', 'english', 'utf-8'),
(438, 'Immigration Notes and Citations', 'Immigration Notes and Citations', 'english', 'utf-8'),
(439, 'Immigration Notes and Sources', 'Immigration Notes and Sources', 'english', 'utf-8'),
(440, 'Immigration Source', 'Immigration Source', 'english', 'utf-8'),
(441, 'Immigration Sources', 'Immigration Sources', 'english', 'utf-8'),
(442, 'Import', 'Import', 'english', 'utf-8'),
(443, 'Import a big GEDCOM file:', 'Import a big GEDCOM file:', 'english', 'utf-8'),
(444, 'Import a GEDCOM file:', 'Import a GEDCOM file:', 'english', 'utf-8'),
(445, 'Import a Language File', 'Import a Language File', 'english', 'utf-8'),
(446, 'Import a tar.gz file to your $g gallery', 'Import a tar.gz file to your $g gallery', 'english', 'utf-8'),
(447, 'Import compressed', 'Import compressed', 'english', 'utf-8'),
(448, 'Import GEDCOM', 'Import GEDCOM', 'english', 'utf-8'),
(449, 'Import/Export languages', 'Import/Export languages', 'english', 'utf-8'),
(450, 'Importing a GEDCOM file to your tree will', 'Importing a GEDCOM file to your tree will', 'english', 'utf-8'),
(451, 'impp_txt_1', 'This tool allows a mass-import of many portraits to your family tree, and is useful when restoring a backup of your tree. It is recommended that a tar.gz file produced by the export tool is used when importing.', 'english', 'utf-8'),
(452, 'impp_txt_2', 'One or more portraits could not be imported. Most likely, this is because some files did not have names that include GEDCOM ID# . Please use the export tool to create a tar.gz portrait file.', 'english', 'utf-8'),
(453, 'imp_gal_1', 'Using this tool, you can upload a set of images all at once to your gallery. The image titles will be auto-generated, and can be edited after uploading. The files must be compressed in the tar.gz format, and your web server must support decompression of this format.', 'english', 'utf-8'),
(454, 'in law', 'in law', 'english', 'utf-8'),
(455, 'Incorrect ID or Xtag Information', 'Incorrect ID or Xtag Information', 'english', 'utf-8'),
(456, 'Individual #ID $ID is not a member of any family', 'Individual #ID $ID is not a member of any family', 'english', 'utf-8'),
(457, 'Individual ID', 'Individual ID', 'english', 'utf-8'),
(458, 'Individual with ID $sID not found', 'Individual with ID $sID not found', 'english', 'utf-8'),
(459, 'Information Hide', 'Information Hide', 'english', 'utf-8'),
(460, 'Information successfully updated', 'Information successfully updated', 'english', 'utf-8'),
(461, 'Initials', 'Initials', 'english', 'utf-8'),
(462, 'installed_on', ',\r\n        installed on the server. Many web hosts offer a service like this for\r\n        free. If the URL starts with https:// instead of http:// then you know\r\n        that the transmission is secure.', 'english', 'utf-8'),
(463, 'Invalid Birth Date', 'Invalid Birth Date', 'english', 'utf-8'),
(464, 'Invalid Date', 'Invalid Date', 'english', 'utf-8'),
(465, 'Invalid Death Date', 'Invalid Death Date', 'english', 'utf-8'),
(466, 'Invalid email address', 'Invalid email address', 'english', 'utf-8'),
(467, 'is', 'is', 'english', 'utf-8'),
(468, 'is invalid! File NOT removed.', 'is invalid! File NOT removed.', 'english', 'utf-8'),
(469, 'Is my password and\r\nusername secure?', 'Is my password and\r\nusername secure?', 'english', 'utf-8'),
(470, 'Is my tree secure?', 'Is my tree secure?', 'english', 'utf-8'),
(471, 'is not listed here, but', 'is not listed here, but', 'english', 'utf-8'),
(472, 'is not listed, then a record will not be created for this new', 'is not listed, then a record will not be created for this new', 'english', 'utf-8'),
(473, 'is the', 'is the', 'english', 'utf-8'),
(474, 'it_is_standard_practice', 'It is standard practice to include some information\r\n    about the &quot;submitter&quot; of the GEDCOM file (your information):', 'english', 'utf-8'),
(475, 'it_is_strongly', 'It is strongly recommended that you save this information after completing\r\n              each section by clicking &quot;Save Information&quot;. In the\r\n              event of a network failure, web browser crash, etc., this will reduce\r\n              your information loss. When entering DATE information, you may enter an exact date using the month,\r\n              day, and year drop-down lists, OR you may enter a text approximation of a date, for example, "circa 1800" or "1850/1851"', 'english', 'utf-8'),
(476, 'i_have_a_large_tree', 'I have a very large tree and want to jump to a specific\r\n     person.', 'english', 'utf-8'),
(477, 'Jump to...', 'Jump to...', 'english', 'utf-8'),
(478, 'Language Name', 'Language Name', 'english', 'utf-8'),
(479, 'Language:', 'Language:', 'english', 'utf-8'),
(480, 'Last Login:', 'Last Login:', 'english', 'utf-8'),
(481, 'Last Login: $lastLogin', 'Last Login: $lastLogin', 'english', 'utf-8'),
(482, 'Lateral Tree', 'Lateral Tree', 'english', 'utf-8'),
(483, 'Lateral View', 'Lateral View', 'english', 'utf-8'),
(484, 'latest version of Internet Explorer', 'latest version of Internet Explorer', 'english', 'utf-8'),
(485, 'LDS Baptism', 'LDS Baptism', 'english', 'utf-8'),
(486, 'LDS Confirmation', 'LDS Confirmation', 'english', 'utf-8'),
(487, 'LDS Endowment', 'LDS Endowment', 'english', 'utf-8'),
(488, 'level', 'level', 'english', 'utf-8'),
(489, 'Life events for $nm', 'Life events for $nm', 'english', 'utf-8'),
(490, 'Life Partners', 'Life Partners', 'english', 'utf-8'),
(491, 'Links Gallery', 'Links Gallery', 'english', 'utf-8'),
(492, 'Load', 'Load', 'english', 'utf-8'),
(493, 'Load Current', 'Load Current', 'english', 'utf-8'),
(494, 'Load Record', 'Load Record', 'english', 'utf-8'),
(495, 'Location', 'Location', 'english', 'utf-8'),
(496, 'Location of Adoption', 'Location of Adoption', 'english', 'utf-8'),
(497, 'Lock password or admin password:', 'Lock password or admin password:', 'english', 'utf-8'),
(498, 'Login add problem', 'Login add problem', 'english', 'utf-8'),
(499, 'Login Error', 'Login Error', 'english', 'utf-8'),
(500, 'Login password', 'Login password', 'english', 'utf-8'),
(501, 'Login Type', 'Login Type', 'english', 'utf-8'),
(502, 'Login username', 'Login username', 'english', 'utf-8'),
(503, 'Logout', 'Logout', 'english', 'utf-8'),
(504, 'logout, then login again', 'logout, then login again', 'english', 'utf-8'),
(505, 'logsp1', 'Please contact the', 'english', 'utf-8'),
(506, 'logsp2', 'with any questions about this family tree system, or if you have any difficulty accessing or using your family tree.', 'english', 'utf-8'),
(507, 'Mail message:', 'Mail message:', 'english', 'utf-8'),
(508, 'Male', 'Male', 'english', 'utf-8'),
(509, 'Male offspring', 'Male offspring', 'english', 'utf-8'),
(510, 'Marriage Agency', 'Marriage Agency', 'english', 'utf-8'),
(511, 'Marriage Citations', 'Marriage Citations', 'english', 'utf-8'),
(512, 'Marriage Contract', 'Marriage Contract', 'english', 'utf-8'),
(513, 'Marriage Date', 'Marriage Date', 'english', 'utf-8'),
(514, 'Marriage events', 'Marriage events', 'english', 'utf-8'),
(515, 'Marriage Information', 'Marriage Information', 'english', 'utf-8'),
(516, 'Marriage License', 'Marriage License', 'english', 'utf-8'),
(517, 'Marriage Notes', 'Marriage Notes', 'english', 'utf-8'),
(518, 'Marriage Notes and Citations', 'Marriage Notes and Citations', 'english', 'utf-8'),
(519, 'Marriage Notes and Sources', 'Marriage Notes and Sources', 'english', 'utf-8'),
(520, 'Marriage Notice', 'Marriage Notice', 'english', 'utf-8'),
(521, 'Marriage Settlement', 'Marriage Settlement', 'english', 'utf-8'),
(522, 'Marriage Sources', 'Marriage Sources', 'english', 'utf-8'),
(523, 'Married', 'Married', 'english', 'utf-8'),
(524, 'Match percentage:', 'Match percentage:', 'english', 'utf-8'),
(525, 'Maternal Ancestry', 'Maternal Ancestry', 'english', 'utf-8'),
(526, 'Mates', 'Mates', 'english', 'utf-8'),
(527, 'Message:', 'Message:', 'english', 'utf-8'),
(528, 'Military service', 'Military service', 'english', 'utf-8'),
(529, 'Minimal/Name Only', 'Minimal/Name Only', 'english', 'utf-8'),
(530, 'mother', 'mother', 'english', 'utf-8'),
(531, 'Mother', 'Mother', 'english', 'utf-8'),
(532, 'Mother:', 'Mother:', 'english', 'utf-8'),
(533, 'MySQL connection to $dbName is good.', 'MySQL connection to $dbName is good.', 'english', 'utf-8'),
(534, 'Name', 'Name', 'english', 'utf-8'),
(535, 'name fragment', 'name fragment', 'english', 'utf-8'),
(536, 'name is', 'name is', 'english', 'utf-8'),
(537, 'Name Prefix', 'Name Prefix', 'english', 'utf-8'),
(538, 'Name Suffix', 'Name Suffix', 'english', 'utf-8'),
(539, 'Naturalization', 'Naturalization', 'english', 'utf-8'),
(540, 'Navigation', 'Navigation', 'english', 'utf-8'),
(541, 'nephew', 'nephew', 'english', 'utf-8'),
(542, 'new_sinfo', 'Please save this record before adding Notes and Sources.', 'english', 'utf-8'),
(543, 'new_sinfo_2', 'Please save this record before adding Life events.', 'english', 'utf-8'),
(544, 'Next Image', 'Next Image', 'english', 'utf-8'),
(545, 'Nickname', 'Nickname', 'english', 'utf-8'),
(546, 'niece', 'niece', 'english', 'utf-8'),
(547, 'Nieces &amp; Nephews:', 'Nieces &amp; Nephews:', 'english', 'utf-8'),
(548, 'nieces and nephews', 'nieces and nephews', 'english', 'utf-8'),
(549, 'nineth', 'nineth', 'english', 'utf-8'),
(550, 'No dam', 'No dam', 'english', 'utf-8'),
(551, 'No father', 'No father', 'english', 'utf-8'),
(552, 'No Images', 'No Images', 'english', 'utf-8'),
(553, 'No marriage information present.', 'No marriage information present.', 'english', 'utf-8'),
(554, 'No mother', 'No mother', 'english', 'utf-8'),
(555, 'No other additional information has been entered for', 'No other additional information has been entered for', 'english', 'utf-8'),
(556, 'No partner information present.', 'No partner information present.', 'english', 'utf-8'),
(557, 'No records in any other trees were returned by your search request.', 'No records in any other trees were returned by your search request.', 'english', 'utf-8'),
(558, 'No records in the', 'No records in the', 'english', 'utf-8'),
(559, 'No sire', 'No sire', 'english', 'utf-8'),
(560, 'No spousal or partner information present', 'No spousal or partner information present', 'english', 'utf-8'),
(561, 'Non family members', 'Non family members', 'english', 'utf-8'),
(562, 'Note # $mid has been deleted successfully.', 'Note # $mid has been deleted successfully.', 'english', 'utf-8'),
(563, 'Note list is empty', 'Note list is empty', 'english', 'utf-8'),
(564, 'NOTE: A copy of this message will be sent to the address specified in the ''From'' field. You may want to add more information about the match or include your name and additional contact information. The message above is just provided as a guideline.', 'NOTE: A copy of this message will be sent to the address specified in the ''From'' field. You may want to add more information about the match or include your name and additional contact information. The message above is just provided as a guideline.', 'english', 'utf-8'),
(565, 'NOTE: Deleting a record will remove ALL references to this person, as well as the biography and photo for the person, if present. After deletion, the next-of-kin for the deleted individual will be loaded. If no next-of-kin is present, the entire family tree list will be loaded.', 'NOTE: Deleting a record will remove ALL references to this person, as well as the biography and photo for the person, if present. After deletion, the next-of-kin for the deleted individual will be loaded. If no next-of-kin is present, the entire family tree list will be loaded.', 'english', 'utf-8'),
(566, 'NOTE: If the', 'NOTE: If the', 'english', 'utf-8'),
(567, 'Note: Uploading a portrait or biography will', 'Note: Uploading a portrait or biography will', 'english', 'utf-8'),
(568, 'Notes', 'Notes', 'english', 'utf-8'),
(569, 'Notes About the Bar/Bat Mitzvah', 'Notes About the Bar/Bat Mitzvah', 'english', 'utf-8');

-- -------------------------------------------------------------
INSERT INTO `[prefix]lang` (`id`, `w`, `m`, `l`, `enc`) VALUES
(570, 'Notes About the Birth', 'Notes About the Birth', 'english', 'utf-8'),
(571, 'Notes About the Death', 'Notes About the Death', 'english', 'utf-8'),
(572, 'Notes and Sources', 'Notes and Sources', 'english', 'utf-8'),
(573, 'Notes delete problem.', 'Notes delete problem.', 'english', 'utf-8'),
(574, 'Notes were deleted successfully.', 'Notes were deleted successfully.', 'english', 'utf-8'),
(575, 'NOTICE: TUFaT could not find a valid temp directory in which to store image data. You will not be able to upload and display portraits correctly without this directory. Please refer to the TUFaT README file for directions on setting up the temp folder.', 'NOTICE: TUFaT could not find a valid temp directory in which to store image data. You will not be able to upload and display portraits correctly without this directory. Please refer to the TUFaT README file for directions on setting up the temp folder.', 'english', 'utf-8'),
(576, 'NOTICE: TUFaT has detected that the temp directory is not world-writeable and/or world-readable. Portraits that you upload will not be correctly displayed unless the temp directory is world-writeable and world-readable.', 'NOTICE: TUFaT has detected that the temp directory is not world-writeable and/or world-readable. Portraits that you upload will not be correctly displayed unless the temp directory is world-writeable and world-readable.', 'english', 'utf-8'),
(577, 'Now sending mail to:', 'Now sending mail to:', 'english', 'utf-8'),
(578, 'no_website', 'No website is necessarily permanent. Hosting companies\r\n        go out of business, system admins die or are laid off, etc. It''s a good\r\n        idea to backup the tree on your own periodically by exporting your tree\r\n        to the GEDCOM file format and saving any biographical and photo files\r\n        that family members may have uploaded. You should also keep a written\r\n        record of your tree and update it as family members make their own contributions\r\n        to your family tree.', 'english', 'utf-8'),
(579, 'Number of records in found:', 'Number of records in found set for  tree:', 'english', 'utf-8'),
(580, 'number of results to return', 'number of results to return', 'english', 'utf-8'),
(581, 'Occupation', 'Occupation', 'english', 'utf-8'),
(582, 'occupation fragment', 'occupation fragment', 'english', 'utf-8'),
(583, 'of', 'of', 'english', 'utf-8'),
(584, 'of this new', 'of this new', 'english', 'utf-8'),
(585, 'of_tufat', 'of Tufat\r\n                v.2. Please do not put *permanent* data\r\n                into it because I cannot guarantee its persistency.\r\n                Please report bugs and suggestions for improvement\r\n                to g8z@yahoo.com. To login as an', 'english', 'utf-8'),
(586, 'once', 'once', 'english', 'utf-8'),
(587, 'Only the', 'Only the', 'english', 'utf-8'),
(588, 'Only the $user tree will be removed.', 'Only the $user tree will be removed.', 'english', 'utf-8'),
(589, 'only those with biographies', 'only those with biographies', 'english', 'utf-8'),
(590, 'only those with portraits', 'only those with portraits', 'english', 'utf-8'),
(591, 'Option A', 'Option A', 'english', 'utf-8'),
(592, 'Option A: choose an existing person as Father, or', 'Option A: choose an existing person as the Father, or', 'english', 'utf-8'),
(593, 'Option A: choose an existing person as Mother, or', 'Option A: choose an existing person as Mother, or', 'english', 'utf-8'),
(594, 'Option A: choose an existing person as the daughter, or', 'Option A: choose an existing person as the daughter, or', 'english', 'utf-8'),
(595, 'Option A: choose an existing person as the sibling, or', 'Option A: choose an existing person as the sibling, or', 'english', 'utf-8'),
(596, 'Option A: choose an existing person as the son, or', 'Option A: choose an existing person as the son, or', 'english', 'utf-8'),
(597, 'Option A: choose an existing person as the spouse, or', 'Option A: choose an existing person as the spouse, or', 'english', 'utf-8'),
(598, 'Option B', 'Option B', 'english', 'utf-8'),
(599, 'Option B: create a new individual as Father', 'Option B: create a new individual as Father', 'english', 'utf-8'),
(600, 'Option B: create a new individual as Mother', 'Option B: create a new individual as Mother', 'english', 'utf-8'),
(601, 'Option B: create a new individual as the daughter', 'Option B: create a new individual as the daughter', 'english', 'utf-8'),
(602, 'Option B: create a new individual as the sibling', 'Option B: create a new individual as the sibling', 'english', 'utf-8'),
(603, 'Option B: create a new individual as the son', 'Option B: create a new individual as the son', 'english', 'utf-8'),
(604, 'Option B: create a new individual as the spouse', 'Option B: create a new individual as the spouse', 'english', 'utf-8'),
(605, 'or', 'or', 'english', 'utf-8'),
(606, 'or enter a valid record number in the navigation bar at the left.', 'or enter a valid record number in the navigation bar at the left.', 'english', 'utf-8'),
(607, 'Ordination', 'Ordination', 'english', 'utf-8'),
(608, 'Other Life Events', 'Other Life Events', 'english', 'utf-8'),
(609, 'Our Family Tree', 'Our Family Tree', 'english', 'utf-8'),
(610, 'Our family trees may have a common link', 'Our family trees may have a common link', 'english', 'utf-8'),
(611, 'Owner', 'Owner', 'english', 'utf-8'),
(612, 'Owner Information (last known)', 'Owner Information (last known)', 'english', 'utf-8'),
(613, 'Page Number', 'Page Number', 'english', 'utf-8'),
(614, 'parents', 'parents', 'english', 'utf-8'),
(615, 'Password:', 'Password:', 'english', 'utf-8'),
(616, 'Paternal Ancestry', 'Paternal Ancestry', 'english', 'utf-8'),
(617, 'PERMANENTLY', 'PERMANENTLY', 'english', 'utf-8'),
(618, 'Permanently Delete the', 'Permanently Delete the', 'english', 'utf-8'),
(619, 'Permanently Delete the $user', 'Permanently Delete the $user', 'english', 'utf-8'),
(620, 'permanently erase', 'permanently erase', 'english', 'utf-8'),
(621, 'Permanently Remove', 'Permanently Remove', 'english', 'utf-8'),
(622, 'person', 'person', 'english', 'utf-8'),
(623, 'Phone', 'Phone', 'english', 'utf-8'),
(624, 'Phone Number', 'Phone Number', 'english', 'utf-8'),
(625, 'pixels will be resized)', 'pixels will be resized)', 'english', 'utf-8'),
(626, 'Place of Adoption', 'Place of Adoption', 'english', 'utf-8'),
(627, 'Place of Baptism', 'Place of Baptism', 'english', 'utf-8'),
(628, 'Place of Bar/Bat Mitzvah', 'Place of Bar/Bat Mitzvah', 'english', 'utf-8'),
(629, 'Place of Birth', 'Place of Birth', 'english', 'utf-8'),
(630, 'Place of Confirmation', 'Place of Confirmation', 'english', 'utf-8'),
(631, 'Place of Death', 'Place of Death', 'english', 'utf-8'),
(632, 'Place of Divorce', 'Place of Divorce', 'english', 'utf-8'),
(633, 'Place of Graduation', 'Place of Graduation', 'english', 'utf-8'),
(634, 'Place of Marriage', 'Place of Marriage', 'english', 'utf-8'),
(635, 'Please choose a file to upload', 'Please choose a file to upload', 'english', 'utf-8'),
(636, 'Please contact the', 'Please contact the', 'english', 'utf-8'),
(637, 'Please enter a password for this new login', 'Please enter a password for this new login', 'english', 'utf-8'),
(638, 'Please login with the new username/password', 'Please login with the new username/password', 'english', 'utf-8'),
(639, 'Please Read Guidelines', 'Please Read Guidelines', 'english', 'utf-8'),
(640, 'Please read these guidelines first', 'Please read these guidelines first', 'english', 'utf-8'),
(641, 'Please select Individual ID from the drop down box', 'Please select Individual ID from the drop down box', 'english', 'utf-8'),
(642, 'Please try a different ID#, or switch to', 'Please try a different ID#, or switch to', 'english', 'utf-8'),
(643, 'Postal Code', 'Postal Code', 'english', 'utf-8'),
(644, 'Previous Image', 'Previous Image', 'english', 'utf-8'),
(645, 'Probate', 'Probate', 'english', 'utf-8'),
(646, 'Process', 'Process', 'english', 'utf-8'),
(647, 'Publication', 'Publication', 'english', 'utf-8'),
(648, 'Re-load $tname''s record.', 'Re-load $tname''s record.', 'english', 'utf-8'),
(649, 'Read-only Password:', 'Read-only Password:', 'english', 'utf-8'),
(650, 'record and fill in information about the', 'record and fill in information about the', 'english', 'utf-8'),
(651, 'regarding this error', 'regarding this error', 'english', 'utf-8'),
(652, 'Registered Name', 'Registered Name', 'english', 'utf-8'),
(653, 'Registration', 'Registration', 'english', 'utf-8'),
(654, 'regname fragment', 'registration name', 'english', 'utf-8'),
(655, 'Relation:', 'Relation:', 'english', 'utf-8'),
(656, 'Reliability', 'Reliability', 'english', 'utf-8'),
(657, 'removed', 'removed', 'english', 'utf-8'),
(658, 'req_pass_text', 'If you do not know the password for your family tree, you may ask your tree administrator for a password. Please enter the tree name, your name, and a way for the administrator to contact you, like an email address or phone number.', 'english', 'utf-8'),
(659, 'Residence', 'Residence', 'english', 'utf-8'),
(660, 'Retirement', 'Retirement', 'english', 'utf-8'),
(661, 'Save Information', 'Save Information', 'english', 'utf-8'),
(662, 'scroll_flow', 'Note: You may need to scroll down and right to see chart', 'english', 'utf-8'),
(663, 'Search', 'Search', 'english', 'utf-8'),
(664, 'Search Again', 'Search Again', 'english', 'utf-8'),
(665, 'search all trees', 'search all trees', 'english', 'utf-8'),
(666, 'Search results for trees other than the', 'Search results for trees other than the', 'english', 'utf-8'),
(667, 'Search your family tree!', 'Search your family tree!', 'english', 'utf-8'),
(668, 'second', 'second', 'english', 'utf-8'),
(669, 'Send Message', 'Send Message', 'english', 'utf-8'),
(670, 'Send Request', 'Send Request', 'english', 'utf-8'),
(671, 'Sender, Recipient, Subject, and Message Text are all required.', 'Sender, Recipient, Subject, and Message Text are all required.', 'english', 'utf-8'),
(672, 'sent_not_ok', 'Tufat Forgotten Password email send problem', 'english', 'utf-8'),
(673, 'server_tufat', 'If your tree is on tufat.com, then family trees are\r\n        backed up weekly. If your tree was created on some other server, then\r\n        you should contact the administrator of that server to find out how often\r\n        backups are performed.', 'english', 'utf-8'),
(674, 'seventh', 'seventh', 'english', 'utf-8'),
(675, 'Show', 'Show', 'english', 'utf-8'),
(676, 'Siblings', 'Siblings', 'english', 'utf-8'),
(677, 'Siblings:', 'Siblings:', 'english', 'utf-8'),
(678, 'simply_close', 'Simply close your web browser to end your TUFaT session.\r\n        If you want to re-login using a different username and password (e.g.\r\n        to access another tree, or to login as an administrator), you may click\r\n        the Logout link in the left navigation area.', 'english', 'utf-8'),
(679, 'since_i_created', 'Since I created a TUFaT tree for my own family, I''ve discovered relatives that\r\n  I never knew I had, and found ancestors reaching back hundreds of years. This\r\n  is because some computer-savvy grandparents and great-uncles that I have entered\r\n  information into TUFaT after I gave them the appropriate login information.\r\n  A decentralized system like this one is FAR superior than online capabilities\r\n  that come with such desktop family tree software like Generations <sup>TM</sup>,\r\n  because with those software products, you create the tree on your desktop computer,\r\n  and then upload *static* pages to a web server. If you want to change the online\r\n  tree, you have to make the change on your desktop computer, and then *re-load*\r\n  to the web. How laborious!', 'english', 'utf-8'),
(680, 'Sire', 'Sire', 'english', 'utf-8'),
(681, 'Sire:', 'Sire:', 'english', 'utf-8'),
(682, 'site supervisor', 'site supervisor', 'english', 'utf-8'),
(683, 'sixth', 'sixth', 'english', 'utf-8'),
(684, 'Size:', 'Size:', 'english', 'utf-8'),
(685, 'somewhat_usernames', 'Somewhat. Usernames and passwords are stored in a\r\n        MySQL table, but they are not encrypted. So unless someone gains access\r\n        to your FTP or MySQL login information, you''re probably ok. However, transmissions\r\n        to and from your computer to the server are not secure unless you have\r\n        an SSL certificate, signed by a trusted authority like', 'english', 'utf-8'),
(686, 'Sons', 'Sons', 'english', 'utf-8'),
(687, 'Sources', 'Sources', 'english', 'utf-8'),
(688, 'Sources delete problem.', 'Sources delete problem.', 'english', 'utf-8'),
(689, 'Sources list is empty', 'Sources list is empty', 'english', 'utf-8'),
(690, 'Sources were deleted successfully.', 'Sources were deleted successfully.', 'english', 'utf-8'),
(691, 'Spouses:', 'Spouses:', 'english', 'utf-8'),
(692, 'Standard', 'Standard', 'english', 'utf-8'),
(693, 'State', 'State', 'english', 'utf-8'),
(694, 'step', 'step', 'english', 'utf-8'),
(695, 'Street Address', 'Street Address', 'english', 'utf-8'),
(696, 'Subject of mail:', 'Subject of mail:', 'english', 'utf-8'),
(697, 'Subject:', 'Subject:', 'english', 'utf-8'),
(698, 'Submit', 'Submit', 'english', 'utf-8'),
(699, 'Submit and Upload more', 'Submit and Upload more', 'english', 'utf-8'),
(700, 'Surname', 'Surname', 'english', 'utf-8'),
(701, 'surname fragment', 'surname fragment', 'english', 'utf-8'),
(702, 'Surname or Family Name', 'Surname or Family Name', 'english', 'utf-8'),
(703, 'Surname Prefix', 'Surname Prefix', 'english', 'utf-8'),
(704, 'Switch to frame view', 'Switch to frame view', 'english', 'utf-8'),
(705, 'Switch to non frame view', 'Switch to non frame view', 'english', 'utf-8'),
(706, 'tags1', '0 @I103@ INDI', 'english', 'utf-8'),
(707, 'tags2', '0 @F100@ FAM', 'english', 'utf-8'),
(708, 'Template Changed', 'Template Changed', 'english', 'utf-8'),
(709, 'tenth', 'tenth', 'english', 'utf-8'),
(710, 'Text Only', 'Text Only', 'english', 'utf-8'),
(711, 'text_e', 'If you do not have a family tree,', 'english', 'utf-8'),
(712, 'the', 'The', 'english', 'utf-8'),
(713, 'The animal is the same', 'The animal is the same', 'english', 'utf-8'),
(714, 'The deletetion has been made.', 'The deletetion has been made.', 'english', 'utf-8'),
(715, 'The e-mail ''to'' address that you have specified appears to contain invalid syntax.', 'The e-mail ''to'' address that you have specified appears to contain invalid syntax.', 'english', 'utf-8'),
(716, 'The events data submission was successful.', 'The events data submission was successful.', 'english', 'utf-8'),
(717, 'The file or file path', 'The file or file path', 'english', 'utf-8'),
(718, 'The following individuals do not belong to a family unit', 'The following individuals do not belong to a family unit', 'english', 'utf-8'),
(719, 'The gallery is empty', 'The gallery is empty', 'english', 'utf-8'),
(720, 'The image has been successfully added to the gallery', 'The image has been successfully added to the gallery', 'english', 'utf-8'),
(721, 'The image has been successfully added to the gallery. You may now add another image, or use the links below to view the gallery or edit your images.', 'The image has been successfully added to the gallery. You may now add another image, or use the links below to view the gallery or edit your images.', 'english', 'utf-8'),
(722, 'The import script does not supports only tar.gz file format.', 'The import script does not supports only tar.gz file format.', 'english', 'utf-8'),
(723, 'The import script supports only tar.gz format.', 'The import script supports only tar.gz format.', 'english', 'utf-8'),
(724, 'The language  with encoding  already exists. Please delete it before importing.', 'The language  with encoding  already exists. Please delete it before importing.', 'english', 'utf-8'),
(725, 'The language save file appears to be invalid.', 'The language save file appears to be invalid.', 'english', 'utf-8'),
(726, 'The link has been successfully added to the gallery', 'The link has been successfully added to the gallery', 'english', 'utf-8'),
(727, 'The link has been successfully updated to the gallery', 'The link has been successfully updated to the gallery', 'english', 'utf-8'),
(728, 'The location specified does not exist or is inaccessible', 'The location specified does not exist or is inaccessible', 'english', 'utf-8'),
(729, 'The login has been added successfully.', 'The login has been added successfully.', 'english', 'utf-8'),
(730, 'The new tree has been created successfully', 'The new tree has been created successfully', 'english', 'utf-8'),
(731, 'The notes submission was successful. Click ''Close'' to close this popup window and add more notes.', 'The notes submission was successful. Click ''Close'' to close this popup window and add more notes.', 'english', 'utf-8'),
(732, 'The notes submission was successful. Click OK to close this popup confirmation and the note editing window, and return to the list of notes', 'The notes submission was successful. Click OK to close this popup confirmation and the note editing window, and return to the list of notes', 'english', 'utf-8'),
(733, 'The person is the same', 'The person is the same', 'english', 'utf-8'),
(734, 'The source has been updated or added successfully. Click OK to close this popup confirmation and the source editing window. The parent window will refresh automatically to reflect this change.', 'The source has been updated or added successfully. Click OK to close this popup confirmation and the source editing window. The parent window will refresh automatically to reflect this change.', 'english', 'utf-8'),
(735, 'The source submission was successful. Click ''Close'' to close this popup window and add more sources.', 'The source submission was successful. Click ''Close'' to close this popup window and add more sources.', 'english', 'utf-8'),
(736, 'The specified individual has no parent information to view.', 'The specified individual has no parent information to view.', 'english', 'utf-8'),
(737, 'The system could not find record with $ID', 'The system could not find record with $ID', 'english', 'utf-8'),
(738, 'The system could not find the individual with ID# $ID', 'The system could not find the individual with ID# $ID', 'english', 'utf-8'),
(739, 'The user name and/or password that you entered could not be found or is invalid. Please try again.', 'The user name and/or password that you entered could not be found or is invalid. Please try again.', 'english', 'utf-8'),
(740, 'The user name that you requested is already in use. Please enter a different one.', 'The user name that you requested is already in use. Please enter a different one.', 'english', 'utf-8'),
(741, 'The username $solduser has been renamed to $suser', 'The username $solduser has been renamed to $suser', 'english', 'utf-8'),
(742, 'The Username $suser is already being used. Please choose another username and try again.', 'The Username $suser is already being used. Please choose another username and try again.', 'english', 'utf-8'),
(743, 'The username $suser with password $spass already exists', 'The username $suser with password $spass already exists', 'english', 'utf-8'),
(744, 'There are no images available.', 'There are no images available.', 'english', 'utf-8'),
(745, 'There are no images present. Click the Add link below to create one.', 'There are no images present. Click the Add link below to create one.', 'english', 'utf-8'),
(746, 'There are no individuals in this family tree yet.', 'There are no individuals in this family tree yet.', 'english', 'utf-8'),
(747, 'There are no uploaded portraits.', 'There are no uploaded portraits.', 'english', 'utf-8'),
(748, 'There has been some problem with renaming username $solduser to $suser', 'There has been some problem with renaming username $solduser to $suser', 'english', 'utf-8'),
(749, 'There was an error sending the e-mail to $emi', 'There was an error sending the e-mail to $emi', 'english', 'utf-8'),
(750, 'There was some add link problem. Please contact your Adminitrator.', 'There was some add link problem. Please contact your Adminitrator.', 'english', 'utf-8'),
(751, 'There was some update problem. Please contact your Adminitrator.', 'There was some update problem. Please contact your Adminitrator.', 'english', 'utf-8'),
(752, 'There was some upload problem. Please contact your Adminitrator.', 'There was some upload problem. Please contact your Adminitrator.', 'english', 'utf-8'),
(753, 'the_gedcom_file', 'The GEDCOM file format is the worldwide standard\r\n              format for storing genealogical information. With this format, you\r\n              will be able to import your tree into other genealogical software,\r\n              like desktop family tree creators and public genealogical databases.', 'english', 'utf-8'),
(754, 'the_gedcom_standard', 'The GEDCOM file format is the standard file format\r\n        used by genealogists to share family tree data electronically. All the\r\n        major family tree creation programs on the market use this format, so\r\n        you can be assured that any tree that is created with this online system\r\n        will be exportable and compatible with most commercial desktop family\r\n        tree creation software.', 'english', 'utf-8'),
(755, 'the_record_that', 'The record that you have requested is\r\n   locked by a password. Please enter it here, or enter the administrator\r\n   password, to continue editing this record.', 'english', 'utf-8'),
(756, 'third', 'third', 'english', 'utf-8'),
(757, 'This is an', 'This is an', 'english', 'utf-8'),
(758, 'This is an automatic notification that an update was made to your family tree record on $today.', 'This is an automatic notification that an update was made to your family tree record on $today.', 'english', 'utf-8'),
(759, 'This record cannot be deleted because the system has found one or more children associated with this record. Its deletion could create a logical inconsistency in the family tree. To delete it, first remove the associated children', 'This record cannot be deleted because the system has found one or more children associated with this record. Its deletion could create a logical inconsistency in the family tree. To delete it, first remove the associated children', 'english', 'utf-8'),
(760, 'this_family', 'This family tree system was created with the expectation that most\r\n  users have Microsoft Internet Explorer. If display problems occur\r\n  while viewing records, try installing the', 'english', 'utf-8'),
(761, 'this_will_create', 'This will create an entirely\r\n                new tree for your extended family. If someone in your extended\r\n                family already has login information for a tree, you should input\r\n                that information into the form bellow instead. The Read-only Password\r\n                will allow users to view, but not edit, the tree, and the Administrative\r\n                Password will allow users to delete the tree, import or export\r\n                data, and bypass any lock. The passwords (general access, read-only, and admin) must be different, and may contain only alpha-numeric characters.', 'english', 'utf-8'),
(762, 'this_will_pdelete', 'This will permanently delete this family tree. ALL\r\n              records and gallery images will be removed. Think about this carefully\r\n              before you do this. If you do not have a backup of the tree, you\r\n              should perform a backup first.', 'english', 'utf-8'),
(763, 'Thumbnail', 'Thumbnail', 'english', 'utf-8'),
(764, 'Time/Date Added', 'Time/Date Added', 'english', 'utf-8'),
(765, 'times', 'times', 'english', 'utf-8'),
(766, 'Title', 'Title', 'english', 'utf-8'),
(767, 'Title:', 'Title:', 'english', 'utf-8'),
(768, 'To logout, you may also simply close all instances of your web browser.', 'To logout, you may also simply close all instances of your web browser.', 'english', 'utf-8'),
(769, 'To view your record click', 'To view your record click', 'english', 'utf-8'),
(770, 'To:', 'To:', 'english', 'utf-8'),
(771, 'Tools', 'Tools', 'english', 'utf-8'),
(772, 'Total number of records:', 'Total number of records in  tree:', 'english', 'utf-8'),
(773, 'to_be_safe', 'To be safe, use a password that you\r\n        don''t mind sharing with others, and do not put information on your web-based\r\n        family tree that is very sensitive. I''m not saying that your information\r\n        is freely visible to anyone who wants it - I''m just saying that if a determined\r\n        hacker wanted to crack your tree, he or she could probably do it. If you\r\n        think about it, your username and password are going to be known by a\r\n        lot of people anyway if you distribute it to many family members, right?\r\n        This is especially true if you have a large family, and many people in\r\n        your family contribute information to the tree. So it doesn''t really make\r\n        sense to use a super private password like your personal bank account\r\n        number of your social security number to protect your tree.', 'english', 'utf-8'),
(774, 'to_jump_to', 'To jump to a specific record, type the record # into\r\n        the &quot;Load Record&quot; field at the right side of the TUFaT screen\r\n        and click OK. It''s a good idea to write down the record # of the person\r\n        you were working on last before ending your web browser session, so that\r\n        you can jump directly to that record later.', 'english', 'utf-8'),
(775, 'to_lock', 'To lock this record, enter a lock password here. Leave this field blank to remove a lock.', 'english', 'utf-8'),
(776, 'to_upload_a_photo', 'To upload a photo to the tree, click on the image\r\n        in the photo frame (where the photo <em>should</em> be), of the currently\r\n        loaded person''s record. Any photo that you load to the tree will replace\r\n        any existing photo.', 'english', 'utf-8'),
(777, 'Tree Created:', 'Tree Created:', 'english', 'utf-8'),
(778, 'Tree Created: $dateCreated', 'Tree Created: $dateCreated', 'english', 'utf-8'),
(779, 'Tree Name', 'Tree Name', 'english', 'utf-8'),
(780, 'Tree Name $tname not found', 'Tree Name $tname not found', 'english', 'utf-8'),
(781, 'Tree Name:', 'Tree Name:', 'english', 'utf-8'),
(782, 'tree were returned by your search request.', 'tree were returned by your search request.', 'english', 'utf-8'),
(783, 'tree will be removed.', 'tree will be removed.', 'english', 'utf-8'),
(784, 'tree:', 'tree:', 'english', 'utf-8'),
(785, 'twice', 'twice', 'english', 'utf-8'),
(786, 'Type of Birth', 'Type of Birth', 'english', 'utf-8'),
(787, 'Type of Union', 'Type of Union', 'english', 'utf-8'),
(788, 'uncle', 'uncle', 'english', 'utf-8'),
(789, 'uncles', 'uncles', 'english', 'utf-8'),
(790, 'Undefined', 'Undefined', 'english', 'utf-8'),
(791, 'Unknown', 'Unknown', 'english', 'utf-8'),
(792, 'Unlock Record', 'Unlock Record', 'english', 'utf-8'),
(793, 'unrecognized_gedcom_tags', 'Unrecognized GEDCOM tags will be ignored during\r\n    the upload. The upload process may take several seconds - please\r\n    be patient.', 'english', 'utf-8'),
(794, 'Update', 'Update', 'english', 'utf-8'),
(795, 'Update Bio or Portrait', 'Update Bio or Portrait', 'english', 'utf-8'),
(796, 'Upload', 'Upload', 'english', 'utf-8'),
(797, 'Upload a new biography for', 'Upload a new biography for', 'english', 'utf-8'),
(798, 'Upload a new biography for $name', 'Upload a new biography for $name', 'english', 'utf-8'),
(799, 'Upload a new portrait for', 'Upload a new portrait for', 'english', 'utf-8'),
(800, 'Upload from FTP, HTTP or server path location:', 'Upload from FTP, HTTP or server path location:', 'english', 'utf-8'),
(801, 'Upload Image:', 'Upload Image:', 'english', 'utf-8'),
(802, 'Upload problem', 'Upload problem', 'english', 'utf-8'),
(803, 'Upload successfull', 'Upload successfull', 'english', 'utf-8'),
(804, 'URL Link:', 'URL Link:', 'english', 'utf-8'),
(805, 'User ID:', 'User ID:', 'english', 'utf-8'),
(806, 'Username Error', 'Username Error', 'english', 'utf-8'),
(807, 'Username should be entered.', 'Username should be entered.', 'english', 'utf-8'),
(808, 'use_admin_pass', ',\r\n                use admin as the password, with your normal user ID. This will\r\n                give you special administrative priviledges, such as the ability\r\n                to import/export records, and bypass any locked record. The admin\r\n                password can be set in the configuration file (which comes with\r\n                the $5 script purchase).', 'english', 'utf-8'),
(809, 'use_at_your_risk', 'Use at your own risk. The creator of TUFaT makes no claim\r\n                  as to the reliability of the system or the consistency of your\r\n                  tree. The system has been rigorously tested, but bugs may have\r\n                  slipped through the testing process.', 'english', 'utf-8'),
(810, 'Vaccination', 'Vaccination', 'english', 'utf-8'),
(811, 'View', 'View', 'english', 'utf-8'),
(812, 'View by', 'View by', 'english', 'utf-8'),
(813, 'View life events', 'View life events', 'english', 'utf-8'),
(814, 'View List', 'View List', 'english', 'utf-8'),
(815, 'View the Gallery', 'View the Gallery', 'english', 'utf-8'),
(816, 'View Thumbnails', 'View Thumbnails', 'english', 'utf-8'),
(817, 'view to choose a different individual.', 'view to choose a different individual.', 'english', 'utf-8'),
(818, 'view_more', 'View More Information About', 'english', 'utf-8'),
(819, 'Welcome to $treeName', 'Welcome to $treeName', 'english', 'utf-8'),
(820, 'Welcome to TUFaT, The Ultimate Family Tree creation system.', 'Welcome to TUFaT, The Ultimate Family Tree creation system.', 'english', 'utf-8'),
(821, 'What is a GEDCOM file?', 'What is a GEDCOM file?', 'english', 'utf-8'),
(822, 'What''s New', 'What''s New', 'english', 'utf-8'),
(823, 'when_uploading', 'When uploading a biographical file, you must specify\r\n        the format of the biography, for example Microsoft Word file, HTML file,\r\n        plain text file, etc. If the biography appears as garbage after uploading,\r\n        then you probably used a text processor that is not supported by this\r\n        system, or you did not specify a file format for the file.', 'english', 'utf-8'),
(824, 'Who is the', 'Who is the', 'english', 'utf-8'),
(825, 'Wife or Female Partner', 'Wife or Female Partner', 'english', 'utf-8'),
(826, 'Will', 'Will', 'english', 'utf-8'),
(827, 'Will my family tree be around for years to come?', 'Will my family tree be around for years to come?', 'english', 'utf-8'),
(828, 'Will my my family tree be around for years to come?', 'Will my my family tree be around for years to come?', 'english', 'utf-8'),
(829, 'With Thumbnail', 'With Thumbnail', 'english', 'utf-8'),
(830, 'Without Thumbnail', 'Without Thumbnail', 'english', 'utf-8'),
(831, 'with_this_online', 'With this online family tree builder, you will\r\n                be able to add to and edit your family tree online. Other members\r\n                of your family may contribute simply by logging in and adding\r\n                their own branches.', 'english', 'utf-8'),
(832, 'with_tufat_you_will', 'With TUFaT, you will be able to dynamically create and update your family tree\r\n  online. This means that the tree will be decentralized, and anyone with the\r\n  appropriate user name and password combination will be able to update their\r\n  information, add their own branches, etc. So go ahead and email your login information\r\n  to as many relatives as you know about, and watch your tree grow!', 'english', 'utf-8'),
(833, 'World Wide Web Address', 'World Wide Web Address', 'english', 'utf-8'),
(834, 'WWW Address', 'WWW Address', 'english', 'utf-8'),
(835, 'Year of Birth', 'Year of Birth', 'english', 'utf-8'),
(836, 'Year of Death', 'Year of Death', 'english', 'utf-8'),
(837, 'You are now logged out of the family tree.', 'You are now logged out of the family tree.', 'english', 'utf-8'),
(838, 'You may choose either:', 'You may choose either:', 'english', 'utf-8'),
(839, 'You must read and consent to the guidelines before creating a family tree.', 'You must read and consent to the guidelines before creating a family tree.', 'english', 'utf-8'),
(840, 'You should login as an Administrator', 'You should login as an Administrator', 'english', 'utf-8'),
(841, 'You will need your family tree login ID and password to access or edit the record.', 'You will need your family tree login ID and password to access or edit the record.', 'english', 'utf-8'),
(842, 'Your changes have been saved. You may now edit another image or use the links below to view, or add to, the gallery', 'Your changes have been saved. You may now edit another image or use the links below to view, or add to, the gallery', 'english', 'utf-8'),
(843, 'Your Name:', 'Your Name:', 'english', 'utf-8'),
(844, 'Your request has been sent to the $tname administrator. If you do not hear from the administrator soon, you may want to contact him or her directly at $aemail', 'Your request has been sent to the $tname administrator. If you do not hear from the administrator soon, you may want to contact him or her directly at $aemail', 'english', 'utf-8'),
(845, 'you_can_enter_adopted', 'You can enter adopted children and domestic partners\r\n        just as you would birth children and married partners. However, bear in\r\n        mind that you family tree would not longer be a genetic tree. It''s a good\r\n        idea to note the adoption or partner in the person''s biographical file.\r\n        In the case of same-sex domestic partners, one of the partners must be\r\n        the &quot;mother&quot; and one must be the &quot;father&quot;. Later releases\r\n        of TUFaT will allow more flexibility in this regard.', 'english', 'utf-8'),
(846, 'you_can_print', 'You can print the webpage that results from the &quot;Entire\r\n        Tree&quot; or &quot;Extended Family&quot; links, or you can export your\r\n        TUFaT tree to the GEDCOM file format and view or print the tree using\r\n        a commerical family tree program. Any program that supports the GEDCOM\r\n        file format should work fine. These programs are usually available at\r\n        local computer stores.', 'english', 'utf-8'),
(847, 'you_will_need', 'You will need to start your tree by creating an individual. This individual\r\n  can be anyone - it doesn''t have to be an ancestor or yourself or anyone in particular.\r\n  Just pick some member of your family at random and enter his or her information\r\n  using the link below.', 'english', 'utf-8'),
(848, 'you_will_need_pe', 'The system is currently being used in "pedigree mode", which means that it will be used to track the genealogy of animals. Some features that are present in "human mode" are not available in "pedigree mode" (how many dogs do you know have occupations?). You can start this pedigree tree with any animal in the lineage, and grow the pedigree from the starting individual.', 'english', 'utf-8');